### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by lambertixx** [investtools/ivttoken-project#55]
## 📝 Description
Error occouring running the project locally.

## 📝 Tasks
- [ ] Search all through the code to find this error
- [ ] Solve the problem
- [ ] Write it down to further implementations

## 💡 Additional Info
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <button> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
